### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by chenruyi** [GitZip/firefox-addons#1]
Failed.
I get following error message in Firefox Quantum 66.0 64-bit.
download a file, the error message:
![image](https://user-images.githubusercontent.com/24762361/54752394-e4057600-4c18-11e9-8df8-90b1bb63ccec.png)

I also used gitzip plugin in Chrome 72,  it work well.

**Comment by chenruyi** [comment]
I try to find the reason, I get following.
![image](https://user-images.githubusercontent.com/24762361/54753242-87578a80-4c1b-11e9-9a7a-74f14ea525d3.png)

**Comment by KinoLien** [comment]
Ok, I finally encountered this error.
And I try to get token again, Github redirects to re-login process. So maybe it means the token has expired.
I will update the message on next version.
