### ISSUE TITLE
There is no Gitzip icon

### ISSUE THREAD

**Issue by runo280** [GitZip/firefox-addons#2]
I faced rate limit error, but there is no Gitzip icon in browser main window (ether overflow section) to authorize it. Also looked at add-ons page and "Customize toolbar" section.

Firefox 67.0

**Comment by runo280** [comment]
OMG, my mistake :(

**Comment by ksar-ksar** [comment]
Hello,

How do you solve your problem ? I have exactly the same one....

**Comment by zjeffer** [comment]
For people getting the same issue, the icon is in the URL bar:

![image](https://user-images.githubusercontent.com/4633209/219743062-b93c6c25-dd89-461b-8f66-a6bd8844f96c.png)
